language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
script: nosetests --nologcapture --all-modules tests
notifications:
  irc:
    - "irc.freenode.org#Hobbestigrou"
  on_success: change
  on_failure: always
  template:
      - "[%{build_number}] %{message} (%{build_url})"
